apiVersion: mirror.openshift.io/v2alpha1
kind: ImageSetConfiguration
mirror:
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.16
    packages:
    - name: netobserv-operator
      channels:
      - name: stable
        minVersion: '1.9.2'
        maxVersion: '1.9.2'
